basePath: /api/v1
definitions:
  handler.HttpMsg:
    properties:
      code:
        type: integer
      msg:
        type: string
    type: object
  model.Product:
    properties:
      created_at:
        type: string
      id:
        type: string
      name:
        type: string
      price:
        type: number
      quantity:
        type: integer
      updated_at:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: charles.tenorio.dev@gmail.com
    name: API Support
    url: http://www.swagger.io/support
  description: API for Faz.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Fazpay API
  version: "1.0"
paths:
  /prd/add:
    post:
      consumes:
      - application/json
      description: Cria um novo produto com base nos dados fornecidos no corpo da
        requisição
      parameters:
      - description: Dados do produto a ser criado
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/model.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Product'
        "400":
          description: Campos obrigatórios não foram fornecidos
          schema:
            $ref: '#/definitions/handler.HttpMsg'
        "500":
          description: Erro ao criar o produto
          schema:
            $ref: '#/definitions/handler.HttpMsg'
      summary: Cria um novo produto
      tags:
      - products
  /prd/all:
    get:
      consumes:
      - application/json
      description: Retorna todos os produtos
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Product'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.HttpMsg'
      summary: Retorna todos os produtos
      tags:
      - products
  /prd/delete/:
    delete:
      consumes:
      - application/json
      description: Exclui um produto com base no ID externo fornecido no cabeçalho
        da requisição
      parameters:
      - description: ID externo do produto
        in: header
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Produto excluído com sucesso
          schema:
            $ref: '#/definitions/handler.HttpMsg'
        "400":
          description: O campo ID é obrigatório
          schema:
            $ref: '#/definitions/handler.HttpMsg'
        "404":
          description: Produto não encontrado
          schema:
            $ref: '#/definitions/handler.HttpMsg'
        "500":
          description: Erro ao excluir o produto
          schema:
            $ref: '#/definitions/handler.HttpMsg'
      summary: Exclui um produto existente
      tags:
      - products
  /prd/getbyid:
    get:
      consumes:
      - application/json
      description: Retorna um produto com base no ID externo fornecido no cabeçalho
        da requisição
      parameters:
      - description: ID externo do produto
        in: header
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Product'
        "400":
          description: O campo ID é obrigatório
          schema:
            $ref: '#/definitions/handler.HttpMsg'
        "404":
          description: Produto não encontrado
          schema:
            $ref: '#/definitions/handler.HttpMsg'
        "500":
          description: Erro ao converter produto para JSON
          schema:
            $ref: '#/definitions/handler.HttpMsg'
      summary: Retorna um produto pelo seu ID externo
      tags:
      - producs
  /prd/update/:
    patch:
      consumes:
      - application/json
      description: Atualiza um produto com base no ID externo fornecido no cabeçalho
        da requisição
      parameters:
      - description: ID externo do produto
        in: header
        name: id
        required: true
        type: string
      - description: Dados do produto a ser atualizado
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/model.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Product'
        "400":
          description: O campo ID é obrigatório
          schema:
            $ref: '#/definitions/handler.HttpMsg'
        "404":
          description: Produto não encontrado
          schema:
            $ref: '#/definitions/handler.HttpMsg'
        "500":
          description: Erro ao atualizar o produto
          schema:
            $ref: '#/definitions/handler.HttpMsg'
      summary: Atualiza um produto existente
      tags:
      - products
swagger: "2.0"
